#!/bin/bash
intltool-extract --type=gettext/glade data/fingwit/fingwit.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=fingwit.pot fingwit data/fingwit/fingwit.ui.h
rm -f data/fingwit/*.ui.h
